
#drop table fff.crop;
use fff;
select * from fff.crop;

insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('wheat', 843, 'cereal', 'suscipit a feugiat et eros', 48.26, 48);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('barley', 273, 'cereal',  null, 11.74, 55);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('oat', 855, 'cereal', null, 89.21, 1);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mangosteen', 880, 'fruit', null, 52.21, 58);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('papaya', 644, 'fruit', null, 79.27, 14);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('soyabean', 963, 'oil and bean', 'erat tortor sollicitudin', 66.76, 48);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('durian', 551, 'fruit', 'a pede posuere nonummy', 90.58, 33);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('tomato', 911, 'vegetable', 'convallis nunc proin at turpis', 80.96, 47);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('potato', 385, 'vegetable', null, 56.33, 64);


insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mango', 319, 'fruit', 'turpis enim blandit mi in', 39.75, 61);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mangosteen', 191, 'fruit', 'eget eleifend luctus ultricies', 11.59, 35);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('rambutan', 958, 'fruit', 'molestie nibh in', 44.67, 49);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('durian', 733, 'fruit', 'quam pede lobortis ligula', 81.95, 40);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('banana', 884, 'fruit', null, 64.51, 14);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('papaya', 782, 'fruit', 'nulla quisque arcu', 43.27, 73);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('barley', 709, 'cereal', 'diam cras pellentesque volutpat', 39.71, 25);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mangosteen', 638, 'fruit', 'magna bibendum imperdiet nullam orci', 51.32, 13);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mango', 883, 'fruit', 'hac habitasse platea dictumst aliquam', 54.24, 29);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('corn', 461, 'cereal', null, 41.33, 58);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('rice', 582, 'rice', 'mollis molestie lorem', 70.22, 42);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mango', 175, 'fruit', null, 19.06, 32);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mangosteen', 725, 'fruit', null, 3.52, 17);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('rice', 322, 'rice', null, 42.82, 23);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('durian', 668, 'fruit', null, 98.92, 23);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('soyabean', 550, 'oil and bean', null, 93.79, 11);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mango', 904, 'fruit', 'scelerisque mauris sit amet eros', 45.84, 46);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('banana', 749, 'fruit', null, 39.28, 27);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('rambutan', 957, 'fruit', 'congue diam id', 53.43, 18);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('barley', 592, 'cereal', 'pede lobortis ligula', 97.36, 52);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('oat', 930, 'cereal', null, 35.01, 46);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('rambutan', 398, 'fruit', null, 50.98, 8);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('rice', 845, 'rice', null, 10.6, 5);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('soyabean', 327, 'oil and bean', null, 85.27, 18);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('peanut', 752, 'oil and bean', 'ligula in lacus curabitur', 88.03, 45);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mangosteen', 435, 'fruit', null, 88.24, 7);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mango', 959, 'fruit', 'vulputate ut ultrices vel', 13.32, 35);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('banana', 955, 'fruit', null, 81.27, 41);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('potato', 402, 'vegetable', 'vitae ipsum aliquam', 51.7, 64);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('wheat', 903, 'cereal', null, 85.82, 46);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('barley', 496, 'cereal', null, 75.71, 48);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('durian', 707, 'fruit', null, 92.37, 66);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('durian', 922, 'fruit', null, 41.1, 54);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('corn', 535, 'cereal', 'sociis natoque penatibus et', 83.82, 54);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('potato', 119, 'vegetable', null, 9.79, 12);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('rice', 732, 'rice', 'parturient montes nascetur', 18.6, 20);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('rambutan', 872, 'fruit', null, 31.52, 65);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('papaya', 426, 'fruit', 'odio odio elementum eu', 41.27, 12);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('potato', 947, 'vegetable', 'tempus vivamus in felis eu', 49.94, 63);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('banana', 576, 'fruit', null, 48.25, 66);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mango', 153, 'fruit', 'sollicitudin ut suscipit', 14.84, 38);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('wheat', 869, 'cereal', 'eros vestibulum ac est', 52.48, 40);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mango', 981, 'fruit', 'penatibus et magnis dis', 19.62, 27);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('barley', 454, 'cereal', 'nisl duis bibendum felis sed', 47.79, 73);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mangosteen', 477, 'fruit', 'potenti nullam porttitor lacus', 62.15, 56);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mangosteen', 852, 'fruit', 'penatibus et magnis dis parturient', 26.11, 58);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('rice', 397, 'rice', null, 87.82, 16);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('banana', 367, 'fruit', null, 2.68, 55);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('durian', 435, 'fruit', null, 71.37, 60);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('durian', 595, 'fruit', 'curae donec pharetra magna', 94.26, 6);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('tomato', 455, 'vegetable', null, 7.38, 23);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('oat', 112, 'cereal', null, 44.39, 14);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('papaya', 864, 'fruit', 'proin interdum mauris non ligula', 90.86, 6);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('corn', 997, 'cereal', 'duis bibendum morbi', 48.24, 29);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mango', 646, 'fruit', null, 59.72, 51);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('peanut', 852, 'oil and bean', null, 59.66, 28);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('rambutan', 807, 'fruit', null, 76.08, 13);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('rambutan', 257, 'fruit', 'ipsum primis in', 6.56, 19);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('wheat', 247, 'cereal', null, 28.95, 43);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mangosteen', 876, 'fruit', null, 82.13, 40);

insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('oat', 555, 'cereal', null, 99.6, 82);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('soyabean', 636, 'oil and bean', null, 39.18, 76);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('rice', 282, 'rice', 'neque libero convallis', 67.83, 82);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('wheat', 349, 'cereal', null, 81.25, 85);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('wheat', 918, 'cereal', 'sit amet nunc viverra', 8.83, 71);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('durian', 948, 'fruit', null, 93.7, 74);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mangosteen', 333, 'fruit', 'arcu adipiscing molestie hendrerit', 61.95, 99);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('durian', 336, 'fruit', 'mollis molestie lorem', 43.6, 91);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mango', 678, 'fruit', 'aliquam augue quam', 7.93, 96);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('potato', 991, 'vegetable', 'sit amet cursus id', 89.73, 86);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mangosteen', 695, 'fruit', 'donec diam neque', 57.31, 98);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mango', 742, 'fruit', 'ipsum aliquam non', 70.05, 84);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('rice', 754, 'rice', 'lacus at velit vivamus', 58.68, 71);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('banana', 981, 'fruit', 'lacinia aenean sit amet', 1.93, 72);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('potato', 539, 'vegetable', null, 16.5, 81);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('banana', 790, 'fruit', null, 5.7, 93);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('corn', 887, 'cereal', 'nisl nunc rhoncus dui vel', 56.44, 92);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('papaya', 607, 'fruit', 'in felis donec', 8.77, 78);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('rice', 638, 'rice', 'sit amet erat nulla', 46.8, 93);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mangosteen', 244, 'fruit', null, 88.23, 90);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mangosteen', 287, 'fruit', 'lacus curabitur at ipsum ac', 59.47, 96);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('barley', 558, 'cereal', 'nulla facilisi cras non', 31.35, 92);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('soyabean', 957, 'oil and bean', 'lobortis est phasellus sit amet', 11.84, 81);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mango', 504, 'fruit', null, 86.76, 71);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mango', 532, 'fruit', 'suspendisse ornare consequat lectus', 16.02, 86);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('tomato', 690, 'vegetable', 'eros elementum pellentesque quisque', 73.47, 87);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('oat', 383, 'cereal', 'nullam molestie nibh in', 55.5, 70);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('peanut', 441, 'oil and bean', 'lacus morbi quis', 57.39, 99);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('rice', 674, 'rice', 'donec semper sapien a', 57.61, 93);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('peanut', 630, 'oil and bean', 'sit amet nulla', 42.26, 77);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('peanut', 479, 'oil and bean', null, 93.64, 84);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('corn', 737, 'cereal', 'in magna bibendum imperdiet', 37.95, 100);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('oat', 159, 'cereal', null, 7.72, 93);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('barley', 924, 'cereal', 'metus vitae ipsum aliquam non', 5.67, 76);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('soyabean', 828, 'oil and bean', null, 69.38, 96);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('potato', 580, 'vegetable', null, 17.32, 71);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('rice', 410, 'rice', 'vel est donec odio', 14.02, 70);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('wheat', 398, 'cereal', 'ac consequat metus', 62.93, 70);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('potato', 640, 'vegetable', 'viverra pede ac diam cras', 65.81, 87);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('rice', 806, 'rice', 'diam vitae quam suspendisse potenti', 35.04, 74);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('barley', 642, 'cereal', null, 6.23, 85);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('corn', 798, 'cereal', 'mauris non ligula pellentesque', 46.79, 71);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mango', 919, 'fruit', null, 81.22, 78);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('corn', 629, 'cereal', 'platea dictumst etiam', 14.21, 84);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('soyabean', 722, 'oil and bean', null, 50.28, 83);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mangosteen', 300, 'fruit', null, 70.54, 76);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('potato', 877, 'vegetable', null, 38.28, 75);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('soyabean', 385, 'oil and bean', 'magna at nunc', 78.57, 83);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('soyabean', 806, 'oil and bean', 'quam sollicitudin vitae consectetuer', 72.89, 75);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mango', 504, 'fruit', 'aliquam non mauris', 47.15, 70);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('wheat', 917, 'cereal', 'sapien non mi integer', 22.0, 75);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('barley', 302, 'cereal', 'nulla justo aliquam', 71.97, 97);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('oat', 712, 'cereal', 'rutrum nulla tellus', 44.88, 75);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('rice', 838, 'rice', 'est quam pharetra magna ac', 18.4, 93);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('wheat', 833, 'cereal', null, 29.11, 90);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('rice', 853, 'rice', 'in porttitor pede justo', 63.11, 96);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mangosteen', 856, 'fruit', null, 69.14, 77);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('mangosteen', 527, 'fruit', 'auctor gravida sem', 82.86, 87);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('tomato', 386, 'vegetable', null, 95.57, 88);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('tomato', 977, 'vegetable', 'scelerisque quam turpis adipiscing', 88.55, 83);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('wheat', 287, 'cereal', 'gravida nisi at nibh in', 68.26, 87);
insert into FFF.crop (cropName, cropQuantity, cropType, cropDescription, priceperUnit, farmerId) values ('rambutan', 994, 'fruit', null, 28.03, 95);